### ISSUE TITLE
ROS2

### ISSUE THREAD

**Issue by AUTOYYJ** [PardisTaghavi/real_time_tracking_AB3DMOT#1]
Thank you for your great work.I was wondering if I could change it to the version of ROS2. Do you have any suggestions on this?

**Comment by PardisTaghavi** [comment]
hello,
unfortunately I don't have the code for ROS2 but this might help:
https://docs.ros.org/en/foxy/The-ROS2-Project/Contributing/Migration-Guide.html#migrating-to-ros-2
