### ISSUE TITLE
ab3dLaunch.launch

### ISSUE THREAD

**Issue by EdisonKevin** [PardisTaghavi/real_time_tracking_AB3DMOT#2]
非常感谢您的工作，我想尝试复现您的代码，运行roslaunch ab3d ab3dLaunch.launch 出现如下错误：
RLException: [ab3dLaunch.launch] is neither a launch file in package [ab3d] nor is [ab3d] a launch file name
The traceback for the exception was written to the log file
排查问题之后发现CMakeLists.txt文件里所有代码已经被注释，catkin_make进行编译时，并没有编译到代码。
不知道是否是CMakeLists.txt文件的问题，非常希望您能解答一下，谢谢

**Comment by PardisTaghavi** [comment]
you need to create the ros package correctly and make sure you are in the correct directory for running launch file.

**Comment by EdisonKevin** [comment]
非常感谢您的回复，但还是遇到一些问题：
我确保已经创建好ros工作空间，并在src目录下放置了相应的代码，在工作空间中进行catkin_make时，可以成功编译，编译完成的页面信息如下：
(base) chen@chen:~/AB3DMOT_ros$ catkin_make
Base path: /home/chen/AB3DMOT_ros
Source space: /home/chen/AB3DMOT_ros/src
Build space: /home/chen/AB3DMOT_ros/build
Devel space: /home/chen/AB3DMOT_ros/devel
Install space: /home/chen/AB3DMOT_ros/install
####
#### Running command: "cmake /home/chen/AB3DMOT_ros/src -DCATKIN_DEVEL_PREFIX=/home/chen/AB3DMOT_ros/devel -DCMAKE_INSTALL_PREFIX=/home/chen/AB3DMOT_ros/install -G Unix Makefiles" in "/home/chen/AB3DMOT_ros/build"
####
-- Using CATKIN_DEVEL_PREFIX: /home/chen/AB3DMOT_ros/devel
-- Using CMAKE_PREFIX_PATH: /home/chen/Fast_lio2_ws/devel;/home/chen/ORB_SLAM3_ws/devel;/opt/ros/noetic
-- This workspace overlays: /home/chen/Fast_lio2_ws/devel;/home/chen/ORB_SLAM3_ws/devel;/opt/ros/noetic
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Using Debian Python package layout
-- Using empy: /usr/lib/python3/dist-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/chen/AB3DMOT_ros/build/test_results
-- Forcing gtest/gmock from source, though one was otherwise available.
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.10") 
-- Using Python nosetests: /usr/bin/nosetests3
-- catkin 0.8.10
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- Configuring done
-- Generating done
-- Build files have been written to: /home/chen/AB3DMOT_ros/build
####
#### Running command: "make -j20 -l20" in "/home/chen/AB3DMOT_ros/build"
####
这似乎没有创建ab3d这个功能包？使用roslaunch ab3d ab3dLaunch.launch启动ROS节点时，还是出现报错，
报错信息如下：
(base) chen@chen:~/AB3DMOT_ros$ roslaunch ab3d ab3dLaunch.launch
RLException: [ab3dLaunch.launch] is neither a launch file in package [ab3d] nor is [ab3d] a launch file name
The traceback for the exception was written to the log file

**Comment by EdisonKevin** [comment]
但是，我尝试指定路径开启launch，开启的指令为：roslaunch src/ab3d/launch/ab3dLaunch.launch，
然仍无法开启节点，报错信息如下：
(base) chen@chen:~/AB3DMOT_ros$ roslaunch src/ab3d/launch/ab3dLaunch.launch 
PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.16.0
NODES
  /
    trackingNode (ab3d/modelROS.py)
auto-starting new master
process[master]: started with pid [7577]
ROS_MASTER_URI=http://localhost:11311
process[rosout-1]: started with pid [7587]
started core service [/rosout]
ERROR: cannot launch node of type [ab3d/modelROS.py]: ab3d
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/chen/AB3DMOT_ros/src
ROS path [2]=/home/chen/Fast_lio2_ws/src
ROS path [3]=/home/chen/ORB_SLAM3_ws/src
ROS path [4]=/opt/ros/noetic/share

不知道上述是否已经正确创建相应的ros功能包？我应该如何正确创建ros功能包，才能正常运行launch 文件里的ros节点modelROS.py，非常希望您能解答一下，谢谢

**Comment by llxClover** [comment]
@EdisonKevin AB3DMOT and mmdetection3d have different environment, eg, python3 version.This is very difficult to deploy, have you succeeded? It doesn't work according to their dependencies.

**Comment by RhythmWings** [comment]
> 非常感谢您的工作，我想尝试复现您的代码，运行roslaunch ab3d ab3dLaunch.launch 出现如下错误： RLException: [ab3dLaunch.launch] is neither a launch file in package [ab3d] nor is [ab3d] a launch file name The traceback for the exception was written to the log file 排查问题之后发现CMakeLists.txt文件里所有代码已经被注释，catkin_make进行编译时，并没有编译到代码。 不知道是否是CMakeLists.txt文件的问题，非常希望您能解答一下，谢谢

请问你成功编译功能包了嘛？我在编译的时候找不到ab3d这个功能包，即使我把它放在了正确的位置（workspace的src下面）。如果可以的话，希望您可以加我的联系方式方便交流，我的QQ号是3356383019（幻夜）

**Comment by sayhiOK** [comment]
Have you solved this problem? @EdisonKevin

**Comment by sayhiOK** [comment]
May I ask if you can answer the above question? @PardisTaghavi

**Comment by RhythmWings** [comment]
> Have you solved this problem? @EdisonKevin

This problem is caused by the missing of package.xml, and you can solve this by coping any package.xml from other ROS tollkit and annotate its dependences, only keep on the compiler.

**Comment by sayhiOK** [comment]
thank you

---- Replied Message ----
| From | ***@***.***> |
| Date | 12/22/2023 17:23 |
| To | PardisTaghavi/real_time_tracking_AB3DMOT ***@***.***> |
| Cc | sayhiOK ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [PardisTaghavi/real_time_tracking_AB3DMOT] ab3dLaunch.launch (Issue #2) |

Have you solved this problem? @EdisonKevin

This problem is caused by the missing of package.xml, and you can solve this by coping any package.xml from other ROS tollkit and annotate its dependences, only keep on the compiler.
