### ISSUE TITLE
ValueError: too many dimensions 'LiDARPoints'

### ISSUE THREAD

**Issue by Pradur241** [PardisTaghavi/real_time_tracking_AB3DMOT#3]
When i run `roslaunch ab3d ab3dLaunch.launch` , i get an Error:

> SUMMARY
> ========
> 
> PARAMETERS
>  * /rosdistro: noetic
>  * /rosversion: 1.16.0
> 
> NODES
>   /
>     trackingNode (ab3d/modelROS.py)
> 
> auto-starting new master
> process[master]: started with pid [116378]
> ROS_MASTER_URI=http://localhost:11311
> 
> setting /run_id to 16922282-31ff-11ee-a69c-8f7c8065d9a3
> process[rosout-1]: started with pid [116388]
> started core service [/rosout]
> process[trackingNode-2]: started with pid [116395]
> tracking node initialzied
> /home/ros/ab3d/src/ab3d/src/mmdetection3d/mmdet3d/models/dense_heads/anchor3d_head.py:94: UserWarning: dir_offset and dir_limit_offset will be depressed and be incorporated into box coder in the future
>   warnings.warn(
> Loads checkpoint by local backend from path: /home/ros/ab3d/src/ab3d/src/mmdetection3d/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth
> /home/ros/ab3d/src/ab3d/src/modelROS.py:92: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
>   self.marker_pub = rospy.Publisher( 'visualization_marker_array', MarkerArray)
> [ERROR] [1691068239.297833]: bad callback: <bound method Subscriber.callback of <message_filters.Subscriber object at 0x7f8e9c536df0>>
> Traceback (most recent call last):
>   File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
>     cb(msg)
>   File "/opt/ros/noetic/lib/python3/dist-packages/message_filters/__init__.py", line 76, in callback
>     self.signalMessage(msg)
>   File "/opt/ros/noetic/lib/python3/dist-packages/message_filters/__init__.py", line 58, in signalMessage
>     cb(*(msg + args))
>   File "/opt/ros/noetic/lib/python3/dist-packages/message_filters/__init__.py", line 330, in add
>     self.signalMessage(*msgs)
>   File "/opt/ros/noetic/lib/python3/dist-packages/message_filters/__init__.py", line 58, in signalMessage
>     cb(*(msg + args))
>   File "/home/ros/ab3d/src/ab3d/src/modelROS.py", line 174, in callbackFunction
>     result, _  = inference_detector(self.model, pointcloud_np)
>   File "/home/ros/ab3d/src/ab3d/src/mmdetection3d/mmdet3d/apis/inference.py", line 175, in inference_detector
>     data_ = test_pipeline(data_)
>   File "/home/ros/anaconda3/envs/AB3D/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 58, in __call__
>     data = t(data)
>   File "/home/ros/anaconda3/envs/AB3D/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
>     return self.transform(results)
>   File "/home/ros/ab3d/src/ab3d/src/mmdetection3d/mmdet3d/datasets/transforms/loading.py", line 742, in transform
>     points = points_class(
>   File "/home/ros/ab3d/src/ab3d/src/mmdetection3d/mmdet3d/structures/points/lidar_points.py", line 34, in __init__
>     super(LiDARPoints, self).__init__(
>   File "/home/ros/ab3d/src/ab3d/src/mmdetection3d/mmdet3d/structures/points/base_points.py", line 41, in __init__
>     tensor = torch.as_tensor(tensor, dtype=torch.float32, device=device)
> ValueError: too many dimensions 'LiDARPoints'

**Comment by gc625-kodifly** [comment]
+1 same problem when running roslaunch and rosbag playing the provided bag file. @PardisTaghavi

**Comment by PleasantPhoenix** [comment]
Hello, I meet the same problem, could you teach me how to solve it?

**Comment by Pradur241** [comment]
We solved the problem by downgrading mmdetection_3d. It works on version 1.0
