### ISSUE TITLE
0000.txt missing

### ISSUE THREAD

**Issue by gc625-kodifly** [PardisTaghavi/real_time_tracking_AB3DMOT#5]
hi, in the modelROS.py you load in a `0000.txt` calib files as follows:

```
calib_path= os.path.join(current_dir, "data/0000.txt")
```

but in the `kitti_calib` file you hardcoded the path:
```
        filepath="/media/avalocal/Samsung_T5/kitti/0000.txt"
```

does this calib file from the kitti dataset?

**Comment by PardisTaghavi** [comment]
Hello,
Yes they are same files and they are both coming from the calib data of Kitti dataset. I just forgot to modify the second file path when I was publishing the code and that is local address of my computer.
