### ISSUE TITLE
ModuleNotFoundError: No module named 'mmdet3d.core'

### ISSUE THREAD

**Issue by PleasantPhoenix** [PardisTaghavi/real_time_tracking_AB3DMOT#8]
![2024-01-04 15-13-36 的屏幕截图](https://github.com/PardisTaghavi/real_time_tracking_AB3DMOT/assets/86542147/0d4007ba-4d33-400d-ba0a-63b91e71fdc8)

**Comment by YoloZyk** [comment]
Did you solve this problem friend, I faced the same problem.

**Comment by csj-github66** [comment]
> 朋友，你解决了这个问题吗，我遇到了同样的问题。
我也


> ![2024-01-04 15-13-36 的屏幕截图](https://private-user-images.githubusercontent.com/86542147/294117321-0d4007ba-4d33-400d-ba0a-63b91e71fdc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMTcyMDcsIm5iZiI6MTczMzIxNjkwNywicGF0aCI6Ii84NjU0MjE0Ny8yOTQxMTczMjEtMGQ0MDA3YmEtNGQzMy00MDBkLWJhMGEtNjNiOTFlNzFmZGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDA5MDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZGE2ZWVmZTRkMmQ0NzY1YjlhNmNkMDMyNjgwYWMxODBmMTI0OWFjNjE0NmFjMDk1ZTVlOTQxOTA2MTViYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5IfgAhXstkBf_SD1daVfAIPfUldIiJ8JpRl7Iu4OXCc)
Have you solved ModuleNotFoundError: No module named ‘mmdet3d.core’ on Jan 4 yet, I'm having this problem too!
