### ISSUE TITLE
The detection box and its annotations in visualization do not correspond to the actual scene.

### ISSUE THREAD

**Issue by PleasantPhoenix** [PardisTaghavi/real_time_tracking_AB3DMOT#9]
Hello, while reproducing your code, I found that the detection boxes and their annotations in the rviz visualization do not correspond to the actual scene. I used the data you shared on the code page. May I know which cailb file you specifically used in the kitti dataset? Is this a problem caused by mismatched cailb files? In addition, I would like to ask if this code can use the bag package collected by oneself. If so, how should the cailb file be processed?

**Comment by PardisTaghavi** [comment]
Hello @PleasantPhoenix , This is the calib file from kitti dataset. Can you please test with this?
https://s3.eu-central-1.amazonaws.com/avg-kitti/raw_data/2011_09_26_calib.zip

**Comment by PleasantPhoenix** [comment]
> Hello @PleasantPhoenix , This is the calib file from kitti dataset. Can you please test with this? https://s3.eu-central-1.amazonaws.com/avg-kitti/raw_data/2011_09_26_calib.zip

Hello, this cailb file and kitti_ The format required in Calib is different, how should I change this format?

**Comment by PleasantPhoenix** [comment]
How do you solve this format problem? I'm sorry, I didn't find the relevant method on the Internet. Can you tell me the conversion method. And have you ever tried to run on your own point cloud data package?Thank you very much

**Comment by PardisTaghavi** [comment]
@PleasantPhoenix  I just uploaded the modified calib txt file. please find it here: https://github.com/PardisTaghavi/real_time_tracking_AB3DMOT/blob/main/src/data/0000.txt 
I did apply the repo on a new data, it does not work very well because the detection model has been trained on kitti and networks trained on pointclouds does not generalize as good as vision networks yet. If you have a detection model trained on your own data, it would fix the problem.

**Comment by PleasantPhoenix** [comment]
@PardisTaghavi  Hello, after making changes to the cailb file, the detection box still doesn't align and the labeled name is incorrect. May I ask where the problem may be? 
![2024-01-07 18-30-00 的屏幕截图](https://github.com/PardisTaghavi/real_time_tracking_AB3DMOT/assets/86542147/4c5c4e92-10f1-4672-a975-41223920552c)
![2024-01-07 10-38-41 的屏幕截图](https://github.com/PardisTaghavi/real_time_tracking_AB3DMOT/assets/86542147/588c0f0d-b1a9-4017-9c69-cb0b32ad0cfd)

**Comment by PardisTaghavi** [comment]
@PleasantPhoenix detections in this scene should be same as the video showed in the repo. I am not sure which part is wrong in your code. If you want send me an email and we can arrange a meeting to look at it. my email: taghavi.pardis@gmail.com

**Comment by PleasantPhoenix** [comment]
@PardisTaghavi Hello, thank you for your reply. I have sent the code to you via email and look forward to your reply.

**Comment by PleasantPhoenix** [comment]
I have found that the problem was caused by a small mistake on my part. I apologize for bothering you for so long.
